### ISSUE TITLE
Null parameters throw exception

### ISSUE THREAD

**Issue by KiaSkretteberg** [ThomasHambach/NcalcJS#10]
I was trying to implement a solution to a problem I was having today which meant that I was passing a value as null, like so:
`exp.Parameters["Field1"] = null`. This, however, does not work as it eventually ends up in this code:
``` 
if (leftValue == null) {
    expression.LeftExpression.Accept(this);
    leftValue = this.Result;
}
```
which doesn't actually work for this situation, as it attempts to create an expression from null and ends up with a "cannot read properties of null" error.

My expression (calculation) is like this:
`if([Field1] == 'Y', [Field2] * 0.2, 0)`
when I'm adding my parameters I have the following code:
```
        let params = calculation.split("[");
        // get rid of the first element because it will always be garbage (either empty or contain an if or something)
        params.shift();
        // loop through each parameter and grab the value from the form
        // and add it's value as a parameter to the expression
        params.forEach(p => {
            p = p.split("]")[0];

            // grab the value corresponding to this parameter
            let field = formValues[p];
            let value = field.value;

            // If the value is an object, grab it's value
            if(value?.value) {
                value = value.value;
            }

            // if it's a number (or doesn't have a type, meaning it's a calculated field), add it as a number
            if(field.type == TypeEnum.Currency || field.type == TypeEnum.Numeric || !field.type) {
                exp.Parameters[p] = Number(value ?? 0);
            // if it's undefined, add it as null
            } else if (typeof value == 'undefined') {
                exp.Parameters[p] = null;
            // otherwise add it as the raw value
            } else {
                exp.Parameters[p] = value;
            }
        });
```
In the above code, a singular formValue takes the format `{type: TypeEnum, value: any}`
The issue I'm running into is I run this code every time a value in the form has changed, so the first time I run it I may only have 1 field defined, so some of them will be undefined. This was causing me issues but I noticed that I thought null handling was better so I decided to set it to null instead. This doesn't seem to have worked though as the null handling does not seem to work. I also tried setting it to undefined, and not setting it at all, none of these worked. Is setting a parameter to null not supported? What is the recommended solution for when an expression needs to use a parameter that doesn't have a value yet?

**Comment by KiaSkretteberg** [comment]
To clarify, in the situation I described above, if Field1 was not yet defined, I would expect my statement to come out as falsey. meaning `if([Field1] == 'Y', [Field2] * 0.2, 0)` would evaluate to 0. If Field2 was not defined, I have it being treated as 0 so the expression should evaluate to 0 as well. I had seen the code that should evaluate the expression should handle null:
```
CompareUsingMostPreciseType(a, b) {
        if (a == null && b == null) {
            return 0;
        }
        if (a == null) {
            return -1;
        }
        if (b == null) {
            return 1;
        }
        if (typeof a == 'number' || typeof b == 'number') {
            if (a < b) {
                return -1;
            }
            else if (a > b) {
                return 1;
            }
            return 0;
        }
        else {
            return a == b ? 0 : 1;
        }
        // return Comparer.Default.Compare(Convert.ChangeType(a, mpt), Convert.ChangeType(b, mpt));
    }
```
but I never make it to this code because it throws an error while trying to determine my left (Field1) value

Edit: For further information, this is specifically where it blows up:
```
VisitIdentifier(parameter) {
        if (Object.prototype.hasOwnProperty.call(this.Parameters, parameter.Name)) {
            // The parameter is defined in the hashtable
            if (this.Parameters[parameter.Name].constructor.name == 'Expression') {
                // The parameter is itself another Expression
                const expression = this.Parameters[parameter.Name];
                // Overloads parameters
                for (const p in this.Parameters) {
                    expression.Parameters[p] = this.Parameters[p];
                }
                expression.EvaluateFunction = this.EvaluateFunction;
                expression.EvaluateParameter = this.EvaluateParameter;
                this.Result = this.Parameters[parameter.Name].Evaluate();
            }
            else {
                this.Result = this.Parameters[parameter.Name];
            }
        }
        else {
            // The parameter should be defined in a call back method
            const args = new _ParameterArgs__WEBPACK_IMPORTED_MODULE_5__.ParameterArgs();
            // Calls external implementation
            this.OnEvaluateParameter(parameter.Name, args);
            if (!args.HasResult)
                throw new ___WEBPACK_IMPORTED_MODULE_0__.ArgumentException(`Parameter '${parameter.Name}' was not defined `);
            this.Result = args.Result;
        }
    }
```
when trying to check the constructor.name on the third line of the function

**Comment by KiaSkretteberg** [comment]
I have found a work around for now. I realized my code that was setting it to null wasn't actually working. However, null still doesn't work as a value, neither does undefined. I instead set it to an empty string and it works. Is this the only/best solution? Should null values work?

**Comment by ThomasHambach** [comment]
Null values aren't really working in the NCALC version in .Net either IIRC. My memory is a bit vague but I remember it throwing exceptions on parsing. I'm not sure whether null values should be accepted. In the end, it's the same as not providing the value?

**Comment by KiaSkretteberg** [comment]
If it doesn't work in the .Net NCalc either then I would say that satisfies my concern as an empty string works for my purposes anyways. Thanks for responding.
