### ISSUE TITLE
Expression.Compile() should be a static method

### ISSUE THREAD

**Issue by robmarti** [ThomasHambach/NcalcJS#13]
In the original .NET version of the package the `Compile()` method is static.
https://github.com/ncalc/ncalc/blob/358ed955dad9f29c9756829c433b2dac63de08ae/src/NCalc/Expression.cs#L119

Since typescript supports static class methods, it would be convenient to mark this method as static in this package as well.
It feels a bit counter intuitive to call `Compile()` on an `Expression` instance.

I currently work around this issue by calling the `Compile` method from the `Expression` prototype
```
Expression.prototype.Compile('9 > 5', true)
```

Please let me know if I should create a PR for this.
Thanks for your work!

**Comment by ThomasHambach** [comment]
Yes please go ahead and make the PR! :) Thank you @robmarti12

**Comment by ThomasHambach** [comment]
@robmarti12 Sweep made an attempt, can you help me check whether that does what you want? :)

**Comment by ThomasHambach** [comment]
Just released 2.1.1 thanks to your help @robmarti12 ! :)
