### ISSUE TITLE
Minification makes NCalcJS unusable

### ISSUE THREAD

**Issue by KiaSkretteberg** [ThomasHambach/NcalcJS#7]
I'm currently attempting to use NCalcJS in an Angular project for performing on the fly calculations on the frontend. We currently use NCalc for C# for another project and wanted to keep the calculation format the same.

The issue we are running into, however, is that when Angular is built for production it minifies the library which breaks the code. The below block of code is the source of the issue. 
```
 Visit(expression) {
        switch (expression.constructor.name) {
            case 'LogicalExpression':
                throw new Error();
            case 'TernaryExpression':
                this.VisitTernary(expression);
                break;
            case 'BinaryExpression':
                this.VisitBinaryExpression(expression);
                break;
            case 'UnaryExpression':
                this.VisitUnaryExpression(expression);
                break;
            case 'ValueExpression':
                this.VisitValueExpression(expression);
                break;
            case 'NCalcFunction':
                this.VisitNCalcFunction(expression);
                break;
            case 'Identifier':
                this.VisitIdentifier(expression);
                break;
            default:
                throw new Error(`Invalid expression type: ${expression.constructor.name}`);
        }
    }
```
This block of code is checking for "expression.constructor.name" which is changed in the minification process. So, for example, "LogicalExpression" may become "g" when minified. This makes it no longer match and breaks everything.

I believe a solution to this would be to add a property onto each of these that could be checked instead of the constructor name but haven't been able to test my theory as of yet and wanted to check if this was a known issue or if there's some other way around it that doesn't involve modifying the code.

**Comment by ThomasHambach** [comment]
Hi @KiaSkretteberg. Good catch. Let me see what I can do.

**Comment by ThomasHambach** [comment]
Can you try the beta release of 2.1.0? This has that issue possibly resolved. I encountered the same issue when using rollup, I just have not gotten around to releasing it fully yet. Refer to NPM [2.1.0-beta3](https://www.npmjs.com/package/ncalcjs/v/2.1.0-beta3)

You can also check the PR here: https://github.com/ThomasHambach/NcalcJS/pull/9

**Comment by KiaSkretteberg** [comment]
Thanks for taking a look at this. I installed 2.1.0-beta3 and it appears to be working properly now and no longer errors when minified. I took a look at the PR and the change looks similar to what I had been thinking would be a solution to the issue. When would you be expecting this version to be getting released?

**Comment by ThomasHambach** [comment]
As soon as we figure out your other issue! Let me close this one and continue in the other issue.
