### ISSUE TITLE
Types are missing when pulling from npm

### ISSUE THREAD

**Issue by KiaSkretteberg** [ThomasHambach/NcalcJS#8]
I tried installing this library from npm using the steps indicated in the readme but had a few issues. 

First:
> Before we can run our build, we need to install ts-patch that will change our paths configured in tsconfig.json. Note that you have to run this every time after running npm install.

> npm run prepare

This instruction is not very clear what it means. What I ended up interpreting it to mean was the following:
1. Install ts-patch (`npm install ts-patch`)
2. Create a command called "prepare" that maps to `ts-patch install` that is run as a postinstall command

I do not know what the purpose of these steps are though as they don't seem to have changed anything at all.

Second: the types file seems to be missing when installing from npm 
![image](https://github.com/ThomasHambach/NcalcJS/assets/9254066/cb7351a7-b2c4-41cb-b110-d5b985eb39e3)
The dist/NCalc folder should have a "types.d.ts" file in it. It exists in the repository but not within npm. I thought perhaps the steps above were supposed to grab the types somehow but they did not. I ended up having to manually download the types.d.ts file and add a postinstall script that would copy the file to the appropriate location in the node modules. Is there a reason it is missing from npm? Is there some step missing from the readme that would pull in the types properly?

**Comment by ThomasHambach** [comment]
Hi @KiaSkretteberg, you only have to type `npm install -s ncalcjs`. The other steps are if you want to build locally. 

As far as I can tell from my projects I use my own library, the types appear to be there. How have you installed or are you using the library?

**Comment by KiaSkretteberg** [comment]
I installed using `npm install ncalcjs` and when trying to run the application I get the error that "../types" couldn't be found when trying to build the application to run it. 
![image](https://github.com/ThomasHambach/NcalcJS/assets/9254066/2fcd37b5-6a71-4517-9ac4-457627579505)

To make sure, I did `npm ci` just now to confirm that with a fresh install I do not get the types. I have 2.0.0 currently. Here is the node module folder for ncalcjs in my project
![image](https://github.com/ThomasHambach/NcalcJS/assets/9254066/b41dfa71-b928-447c-a140-01f15e9e1a85)
The error showing for tsconfig.json indicates: 
> File '/node_modules/ncalcjs/node_modules/jest-expect-message/types/index.d.ts' not found.
  The file is in the program because:
    Part of 'files' list in tsconfig.json

I'm not sure if this is part of the issue as to why the types is not there. As I showed in the previous screenshot of npm the types file does not show anywhere in the list of files so unless it's supposed to come from some other source I'm not sure how I would get it through installing it via npm.

**Comment by ThomasHambach** [comment]
Weird that it is trying to load the type definitions of the jest package. I'll have a look at it and get back to you tomorrow.

**Comment by KiaSkretteberg** [comment]
Just as further information. If I add this file https://github.com/ThomasHambach/NcalcJS/blob/main/src/NCalc/types.d.ts to the node_modules folder at "node_modules/ncalcjs/dist/NCalc" as "types.d.ts" the error stops happening. This is the file that appears to be missing from npm and is causing issues. I'm not sure if any of the information I provided previously explains why this is occurring.

**Comment by ThomasHambach** [comment]
Got it, I seem to have forgotten that `.d.ts` files do not get included in the build. I made a commit https://github.com/ThomasHambach/NcalcJS/pull/9/commits/a13a6d3ca5af6a5fb04bdd8e3b8b83511817e477 here. Can you try installing `ncalcjs@2.1.0-beta4` and let me know if that resolves the issue? Thanks!

**Comment by KiaSkretteberg** [comment]
I tested it out today and I can see the file is in npm. I removed the module to make sure I didn't have the file still hanging around and I can see the types file is there now and I no longer get build errors or any sort of issues.

Thanks for taking a look at this and being fairly speedy with your responses!

**Comment by ThomasHambach** [comment]
Great. Just released 2.1.0. Thanks for reporting.
